// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'dart:io';

/// Platform-specifikus Firebase konfigurációs beállítások
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (Platform.isAndroid) {
      return android;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions have not been configured for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn2w48HjZ6y3KwTk1aCsBj86G3sM8r6Zg',           // api_key from google-services.json
    appId: '1:1060445576585:android:a47247dd728c1ec4e69558',   // mobilesdk_app_id
    messagingSenderId: '1060445576585',                          // project_number ✅
    projectId: 'booknail',                                       // project_id
    databaseURL: 'https://booknail.firebaseio.com',             // booknail (project_id)
    storageBucket: 'booknail.firebasestorage.app',              // storage_bucket
  );
}
